// src/components/BottomToolbar.tsx
import { Button } from './ui/button';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from './ui/tooltip';
import { 
  MousePointer,
  Hand,
  Users,
  MessageSquarePlus,
  Download,
  Settings,
  Zap,
  Link
} from 'lucide-react';

interface BottomToolbarProps {
  selectedTool: 'select' | 'character' | 'message' | 'pan' | 'connect';
  onToolSelect: (tool: 'select' | 'character' | 'message' | 'pan' | 'connect') => void;
  selectedElement?: string | null;
  elementCount?: {
    characters: number;
    messages: number;
    connections: number;
  };
  onExport?: () => void;
  onSettings?: () => void;
}

export function BottomToolbar({
  selectedTool,
  onToolSelect,
  elementCount,
  onExport,
  onSettings
}: BottomToolbarProps) {
  const tools = [
    { 
      id: 'select', 
      icon: MousePointer, 
      label: 'Select', 
      shortcut: 'V',
      description: 'Select, move & connect elements. Hold Shift+Drag for proximity connections',
      color: 'text-gray-700'
    },
    { 
      id: 'pan', 
      icon: Hand, 
      label: 'Pan', 
      shortcut: 'H',
      description: 'Navigate around the canvas',
      color: 'text-gray-700'
    },
    { 
      id: 'connect', 
      icon: Link, 
      label: 'Connect', 
      shortcut: 'L',
      description: 'Drag nodes near each other to auto-connect',
      color: 'text-green-600'
    },
    { 
      id: 'character', 
      icon: Users, 
      label: 'Character', 
      shortcut: 'C',
      description: 'Add new characters',
      color: 'text-blue-600'
    },
    { 
      id: 'message', 
      icon: MessageSquarePlus, 
      label: 'Message', 
      shortcut: 'M',
      description: 'Add chat messages',
      color: 'text-purple-600'
    }
  ];

  const handleToolClick = (toolId: string) => {
    onToolSelect(toolId as any);
  };

  return (
    <div className="h-16 bg-white border-t border-gray-200 flex items-center justify-between px-6 shadow-sm flex-shrink-0">
      {/* Left Stats - Element Count */}
      <div className="flex items-center gap-6">
        {elementCount && (
          <div className="flex items-center gap-4 text-sm text-gray-500">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <div className="flex items-center gap-1.5">
                    <Users className="h-4 w-4" />
                    <span className="font-medium text-gray-700">{elementCount.characters}</span>
                  </div>
                </TooltipTrigger>
                <TooltipContent>
                  {elementCount.characters} character{elementCount.characters !== 1 ? 's' : ''}
                </TooltipContent>
              </Tooltip>

              <Tooltip>
                <TooltipTrigger asChild>
                  <div className="flex items-center gap-1.5">
                    <MessageSquarePlus className="h-4 w-4" />
                    <span className="font-medium text-gray-700">{elementCount.messages}</span>
                  </div>
                </TooltipTrigger>
                <TooltipContent>
                  {elementCount.messages} message{elementCount.messages !== 1 ? 's' : ''}
                </TooltipContent>
              </Tooltip>

              <Tooltip>
                <TooltipTrigger asChild>
                  <div className="flex items-center gap-1.5">
                    <Zap className="h-4 w-4" />
                    <span className="font-medium text-gray-700">{elementCount.connections}</span>
                  </div>
                </TooltipTrigger>
                <TooltipContent>
                  {elementCount.connections} connection{elementCount.connections !== 1 ? 's' : ''}
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        )}
      </div>

      {/* Center Main Tool Selection - Figma Style */}
      <div className="flex items-center">
        <div className="flex items-center bg-gray-50 rounded-lg p-1 border border-gray-200">
          <TooltipProvider>
            {tools.map((tool) => (
              <Tooltip key={tool.id}>
                <TooltipTrigger asChild>
                  <Button
                    variant={selectedTool === tool.id ? 'default' : 'ghost'}
                    size="sm"
                    onClick={() => handleToolClick(tool.id)}
                    className={`
                      h-10 w-10 rounded-md transition-all duration-200 
                      ${selectedTool === tool.id 
                        ? 'bg-white shadow-sm border border-gray-200 text-gray-900' 
                        : 'hover:bg-white hover:shadow-sm hover:border hover:border-gray-200 text-gray-600 hover:text-gray-900'
                      }
                    `}
                  >
                    <tool.icon className="h-4 w-4" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent side="top" className="bg-gray-900 text-white border-gray-700">
                  <div className="space-y-1">
                    <div className="font-medium">{tool.label}</div>
                    <div className="text-xs text-gray-300">{tool.description}</div>
                    <div className="text-xs">
                      Press <kbd className="px-1 py-0.5 bg-gray-700 rounded text-xs">{tool.shortcut}</kbd>
                    </div>
                  </div>
                </TooltipContent>
              </Tooltip>
            ))}
          </TooltipProvider>
        </div>
      </div>

      {/* Right Actions - Minimal */}
      <div className="flex items-center gap-2">
        <TooltipProvider>
          {onExport && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={onExport}
                  className="h-10 w-10 rounded-lg text-gray-600 hover:text-gray-900 hover:bg-gray-100"
                >
                  <Download className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                Export animation
              </TooltipContent>
            </Tooltip>
          )}

          {onSettings && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={onSettings}
                  className="h-10 w-10 rounded-lg text-gray-600 hover:text-gray-900 hover:bg-gray-100"
                >
                  <Settings className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                Settings
              </TooltipContent>
            </Tooltip>
          )}
        </TooltipProvider>
      </div>
    </div>
  );
}

// src/lib/components/workspace/BottomToolbar.svelte
<script lang="ts">
	import type { Tool } from '$lib/types';
	import type { ComponentType } from 'svelte';
	import { Button } from '$lib/components/ui/button';
	import { Separator } from '$lib/components/ui/separator';
	import MousePointer2 from 'lucide-svelte/icons/mouse-pointer-2';
	import Hand from 'lucide-svelte/icons/hand';
	import User from 'lucide-svelte/icons/user';
	import MessageSquare from 'lucide-svelte/icons/message-square';
	import Link2 from 'lucide-svelte/icons/link-2';
	import Copy from 'lucide-svelte/icons/copy';
	import Trash2 from 'lucide-svelte/icons/trash-2';

	interface Props {
		selectedTool: Tool;
		onToolSelect: (tool: Tool) => void;
		selectedElement: string | null;
		elementCount: {
			characters: number;
			messages: number;
			connections: number;
		};
		onDelete?: () => void;
		onDuplicate?: () => void;
	}

	let {
		selectedTool,
		onToolSelect,
		selectedElement,
		elementCount,
		onDelete,
		onDuplicate
	}: Props = $props();

	function handleDelete() {
		if (selectedElement && onDelete) {
			onDelete();
		}
	}

	function handleDuplicate() {
		if (selectedElement && onDuplicate) {
			onDuplicate();
		}
	}

	const tools: Array<{ id: Tool; icon: ComponentType; label: string; shortcut: string }> = [
		{ id: 'select', icon: MousePointer2, label: 'Select', shortcut: 'V' },
		{ id: 'pan', icon: Hand, label: 'Pan', shortcut: 'H' },
		{ id: 'character', icon: User, label: 'Character', shortcut: 'C' },
		{ id: 'message', icon: MessageSquare, label: 'Message', shortcut: 'M' }
	];
</script>

<div class="border-t border-border bg-card px-4 py-3">
	<div class="flex items-center justify-between">
		<!-- Left: Selection Info -->
		<div class="flex items-center gap-3">
			{#if selectedElement}
				<div class="text-sm text-muted-foreground">
					<span class="font-medium text-foreground">Selected:</span>
					{selectedElement.startsWith('char') ? 'Character' : 'Message'}
				</div>
			{:else}
				<div class="text-sm text-muted-foreground">
					No selection
				</div>
			{/if}
		</div>

		<!-- Center: Element Counts -->
		<div class="flex items-center gap-4">
			<div class="flex items-center gap-2">
				<User class="size-4 text-muted-foreground" />
				<span class="text-sm font-medium">{elementCount.characters}</span>
				<span class="text-xs text-muted-foreground">Characters</span>
			</div>
			<div class="flex items-center gap-2">
				<MessageSquare class="size-4 text-muted-foreground" />
				<span class="text-sm font-medium">{elementCount.messages}</span>
				<span class="text-xs text-muted-foreground">Messages</span>
			</div>
			<div class="flex items-center gap-2">
				<Link2 class="size-4 text-muted-foreground" />
				<span class="text-sm font-medium">{elementCount.connections}</span>
				<span class="text-xs text-muted-foreground">Connections</span>
			</div>
		</div>

		<!-- Right: Quick Actions -->
		<div class="flex items-center gap-1">
			<Button 
				variant="ghost" 
				size="sm" 
				disabled={!selectedElement} 
				title="Duplicate (Ctrl+D)"
				onclick={handleDuplicate}
				class="hover:bg-blue-50 hover:text-blue-600"
			>
				<Copy class="size-4" />
			</Button>
			<Button 
				variant="ghost" 
				size="sm" 
				disabled={!selectedElement} 
				title="Delete (Del)"
				onclick={handleDelete}
				class="hover:bg-destructive/10 hover:text-destructive"
			>
				<Trash2 class="size-4" />
			</Button>
		</div>
	</div>
</div>
